In [1]:
import os
import pandas as pd

In [2]:
df = pd.read_csv("ABIDEII-connectomes/ABIDEII_Composite_Phenotypic.csv", encoding="ISO-8859-1")
df

,SITE_ID,SUB_ID,NDAR_GUID,DX_GROUP,PDD_DSM_IV_TR,ASD_DSM_5,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,...,ADI_R_C3_TOTAL,ADI_R_C4_REPETITIVE_USE_OBJECTS,ADI_R_C4_HIGHER,ADI_R_C4_UNUSUAL_SENSORY_INTERESTS,ADI_R_C4_TOTAL,ADI_R_D_AGE_PARENT_NOTICED,ADI_R_D_AGE_FIRST_SINGLE_WORDS,ADI_R_D_AGE_FIRST_PHRASES,ADI_R_D_AGE_WHEN_ABNORMALITY,ADI_R_D_INTERVIEWER_JUDGMENT
0,ABIDEII-BNI_1,29006,NaN,1,NaN,NaN,48.0000,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABIDEII-BNI_1,29007,NaN,1,NaN,NaN,41.0000,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABIDEII-BNI_1,29008,NaN,1,NaN,NaN,59.0000,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABIDEII-BNI_1,29009,NaN,1,NaN,NaN,57.0000,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABIDEII-BNI_1,29010,NaN,1,NaN,NaN,45.0000,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1109,ABIDEII-USM_1,29523,NDARCL516DV3,2,0.0,NaN,36.1451,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1110,ABIDEII-USM_1,29524,NDARKC441AZJ,2,0.0,NaN,11.7892,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1111,ABIDEII-USM_1,29525,NDARCF644GKW,2,0.0,NaN,23.2909,1,1.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1112,ABIDEII-USM_1,29526,NDARLE058ZZK,2,0.0,NaN,32.6242,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1113,ABIDEII-USM_1,29527,NaN,2,0.0,NaN,11.4962,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
list_of_subj = []

for root, dirs, files in os.walk("ABIDEII-connectomes"):
    for f in files:
        filepath = os.path.join(root, f)
        if filepath.find("AAL_space-") + 1:
            list_of_subj.append(int(filepath[filepath.index("sub-") + 4 : filepath.index("sub-") + 9]))

list_of_subj

[29123,
 29127,
 29134,
 29121,
 29133,
 29131,
 29137,
 29119,
 29117,
 29136,
 29130,
 29129,
 29120,
 29126,
 29135,
 29118,
 29128,
 29125,
 29124,
 29044,
 29056,
 29051,
 29049,
 29032,
 29040,
 29018,
 29035,
 30149,
 29022,
 30147,
 29048,
 29034,
 29024,
 29021,
 29014,
 29033,
 29038,
 29016,
 29011,
 29045,
 29020,
 29050,
 29023,
 29019,
 29047,
 30146,
 29054,
 29036,
 28889,
 28878,
 28904,
 28888,
 28868,
 28858,
 28880,
 28886,
 28883,
 28862,
 28895,
 28867,
 28854,
 28900,
 28877,
 28863,
 28891,
 28893,
 28902,
 28882,
 28892,
 28870,
 28894]

In [4]:
df = df.loc[df["SUB_ID"].isin(list_of_subj)]
df

,SITE_ID,SUB_ID,NDAR_GUID,DX_GROUP,PDD_DSM_IV_TR,ASD_DSM_5,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,...,ADI_R_C3_TOTAL,ADI_R_C4_REPETITIVE_USE_OBJECTS,ADI_R_C4_HIGHER,ADI_R_C4_UNUSUAL_SENSORY_INTERESTS,ADI_R_C4_TOTAL,ADI_R_D_AGE_PARENT_NOTICED,ADI_R_D_AGE_FIRST_SINGLE_WORDS,ADI_R_D_AGE_FIRST_PHRASES,ADI_R_D_AGE_WHEN_ABNORMALITY,ADI_R_D_INTERVIEWER_JUDGMENT
29,ABIDEII-BNI_1,29011,NaN,2,NaN,NaN,48.00,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,ABIDEII-BNI_1,29014,NaN,2,NaN,NaN,64.00,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,ABIDEII-BNI_1,29016,NaN,2,NaN,NaN,41.00,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,ABIDEII-BNI_1,29018,NaN,2,NaN,NaN,51.00,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,ABIDEII-BNI_1,29019,NaN,2,NaN,NaN,62.00,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,ABIDEII-TCD_1,29133,NaN,2,0.0,NaN,19.50,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
985,ABIDEII-TCD_1,29134,NaN,2,0.0,NaN,11.00,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986,ABIDEII-TCD_1,29135,NaN,2,0.0,NaN,18.75,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
987,ABIDEII-TCD_1,29136,NaN,2,0.0,NaN,19.00,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
988,ABIDEII-TCD_1,29137,NaN,2,0.0,NaN,13.50,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df = df.dropna(axis=1, how="all")
df

,SITE_ID,SUB_ID,DX_GROUP,PDD_DSM_IV_TR,ASD_DSM_5,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,...,BDI_TOTAL,VMI_EDITION,VMI_VMI_S,CELF_EDITION,CELF_5-8_CORE_S,CELF_5-8_RECEPTIVE_S,CELF_5-8_EXPRESSIVE_S,CELF_9-21_CORE_S,CELF_9-21_RECEPTIVE_S,CELF_9-21_EXPRESSIVE_S
29,ABIDEII-BNI_1,29011,2,NaN,NaN,48.00,1,1.0,NaN,141.0,...,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,ABIDEII-BNI_1,29014,2,NaN,NaN,64.00,1,1.0,NaN,113.0,...,11.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,ABIDEII-BNI_1,29016,2,NaN,NaN,41.00,1,1.0,NaN,106.0,...,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,ABIDEII-BNI_1,29018,2,NaN,NaN,51.00,1,1.0,NaN,127.0,...,8.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,ABIDEII-BNI_1,29019,2,NaN,NaN,62.00,1,1.0,NaN,100.0,...,32.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,ABIDEII-TCD_1,29133,2,0.0,NaN,19.50,1,1.0,NaN,111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
985,ABIDEII-TCD_1,29134,2,0.0,NaN,11.00,1,1.0,NaN,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986,ABIDEII-TCD_1,29135,2,0.0,NaN,18.75,1,1.0,NaN,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
987,ABIDEII-TCD_1,29136,2,0.0,NaN,19.00,1,1.0,NaN,111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
988,ABIDEII-TCD_1,29137,2,0.0,NaN,13.50,1,1.0,NaN,81.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_dummy = df.dropna(axis=1)
df_dummy

,SITE_ID,SUB_ID,DX_GROUP,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,FIQ,FIQ_TEST_TYPE,SRS_EDITION,SRS_VERSION,...,SRS_MANNERISMS_RAW,SRS_TOTAL_T,SRS_AWARENESS_T,SRS_COGNITION_T,SRS_COMMUNICATION_T,SRS_MOTIVATION_T,SRS_MANNERISMS_T,CURRENT_MED_STATUS,CURRENT_MEDICATION_NAME,EYE_STATUS_AT_SCAN
29,ABIDEII-BNI_1,29011,2,48.00,1,1.0,141.0,KBIT-2,2.0,2.0,...,4.0,46.0,47.0,51.0,43.0,47.0,47.0,0.0,none,2.0
30,ABIDEII-BNI_1,29014,2,64.00,1,1.0,113.0,KBIT-2,2.0,2.0,...,6.0,53.0,52.0,51.0,54.0,57.0,50.0,0.0,none,2.0
31,ABIDEII-BNI_1,29016,2,41.00,1,1.0,106.0,KBIT-2,2.0,2.0,...,4.0,50.0,64.0,48.0,47.0,51.0,47.0,0.0,none,2.0
32,ABIDEII-BNI_1,29018,2,51.00,1,1.0,127.0,KBIT-2,2.0,2.0,...,5.0,46.0,47.0,53.0,43.0,42.0,47.0,0.0,none,2.0
33,ABIDEII-BNI_1,29019,2,62.00,1,1.0,100.0,KBIT-2,2.0,2.0,...,10.0,59.0,47.0,72.0,52.0,64.0,57.0,0.0,none,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,ABIDEII-TCD_1,29133,2,19.50,1,1.0,111.0,WASI,1.0,1.0,...,1.0,38.0,35.0,39.0,38.0,42.0,42.0,0.0,none,1.0
985,ABIDEII-TCD_1,29134,2,11.00,1,1.0,116.0,WASI,1.0,1.0,...,5.0,55.0,68.0,48.0,52.0,61.0,51.0,0.0,none,1.0
986,ABIDEII-TCD_1,29135,2,18.75,1,1.0,120.0,WASI,1.0,1.0,...,5.0,48.0,46.0,41.0,45.0,54.0,51.0,0.0,none,1.0
987,ABIDEII-TCD_1,29136,2,19.00,1,1.0,111.0,WASI,1.0,1.0,...,2.0,49.0,46.0,48.0,52.0,61.0,44.0,0.0,none,1.0
988,ABIDEII-TCD_1,29137,2,13.50,1,1.0,81.0,WASI,1.0,1.0,...,6.0,51.0,49.0,39.0,50.0,63.0,53.0,0.0,none,1.0

In [8]:
df_dummy.describe()

,SUB_ID,DX_GROUP,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,FIQ,SRS_EDITION,SRS_VERSION,SRS_INFORMANT,SRS_TOTAL_RAW,...,SRS_MOTIVATION_RAW,SRS_MANNERISMS_RAW,SRS_TOTAL_T,SRS_AWARENESS_T,SRS_COGNITION_T,SRS_COMMUNICATION_T,SRS_MOTIVATION_T,SRS_MANNERISMS_T,CURRENT_MED_STATUS,EYE_STATUS_AT_SCAN
count,71.000000,71.0,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,...,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000
mean,29056.492958,2.0,24.807042,1.028169,1.098592,110.605634,1.408451,1.408451,2.788732,22.746479,...,5.197183,3.000000,45.915493,44.380282,43.746479,43.577465,47.338028,45.746479,0.014085,1.408451
std,250.471605,0.0,15.810793,0.166633,0.419351,13.714933,0.495046,0.495046,2.083373,15.710523,...,4.128714,3.051931,10.485019,9.260309,6.958486,6.298893,7.780826,5.696411,0.118678,0.495046
min,28854.000000,2.0,8.700000,1.000000,1.000000,79.000000,1.000000,1.000000,1.000000,2.000000,...,0.000000,0.000000,35.000000,30.000000,36.000000,36.000000,37.000000,40.000000,0.000000,1.000000
25%,28893.500000,2.0,13.500000,1.000000,1.000000,101.000000,1.000000,1.000000,1.000000,10.000000,...,2.000000,0.000000,39.000000,38.000000,39.000000,38.000000,41.000000,40.000000,0.000000,1.000000
50%,29034.000000,2.0,18.000000,1.000000,1.000000,111.000000,1.000000,1.000000,1.000000,21.000000,...,5.000000,2.000000,44.000000,44.000000,41.000000,43.000000,47.000000,44.000000,0.000000,1.000000
75%,29120.500000,2.0,40.500000,1.000000,1.000000,122.000000,2.000000,2.000000,5.000000,31.500000,...,8.000000,4.000000,49.000000,49.000000,48.000000,47.000000,52.000000,49.000000,0.000000,2.000000
max,30149.000000,2.0,64.000000,2.000000,3.000000,142.000000,2.000000,2.000000,9.000000,70.000000,...,17.000000,12.000000,90.000000,69.000000,72.000000,62.000000,66.000000,65.000000,1.000000,2.000000

In [9]:
df_dummy.to_csv("phenotype.csv")